"""
Serving layer  (Stage 8) — build a BI-style dashboard from the gold marts + metrics layer.

Reads the governed metrics_summary + gold marts from the warehouse and renders a
self-contained HTML dashboard (KPI cards + bar charts) plus metrics.json. In production
the same metrics feed Power BI / Looker / Tableau (see BI_CONNECT.md).
Output: out/dashboard.html, out/metrics.json
"""
from __future__ import annotations
import json
import duckdb
from common import WAREHOUSE, OUT


def _fmt(v):
    try:
        f = float(v)
        return f"{f:,.0f}" if abs(f) >= 1000 else f"{f:,.2f}"
    except Exception:
        return str(v)


def _bars(rows, label_i, val_i, color):
    if not rows:
        return "<p>no data</p>"
    mx = max(float(r[val_i]) for r in rows) or 1
    out = ['<div class="bars">']
    for r in rows:
        w = int(float(r[val_i]) / mx * 100)
        out.append(f'<div class="bar"><span class="bl">{r[label_i]}</span>'
                   f'<span class="bt" style="width:{w}%;background:{color}"></span>'
                   f'<span class="bv">{_fmt(r[val_i])}</span></div>')
    out.append("</div>")
    return "".join(out)


def run():
    con = duckdb.connect(str(WAREHOUSE))
    metrics = {m: v for m, v in con.execute("select metric, value from metrics_summary").fetchall()}
    recon = con.execute("select txn_date, gross_posted, reversals, net_movement from gold_daily_reconciliation order by txn_date").fetchall()
    fraud = con.execute("select country, alerts, alert_rate from gold_fraud_summary order by alerts desc limit 8").fetchall()
    exposure = con.execute("select region||' / '||segment, total_volume from gold_regulatory_exposure order by total_volume desc limit 8").fetchall()
    con.close()

    (OUT / "metrics.json").write_text(json.dumps(metrics, indent=2, default=str))

    kpi = [("Net movement", metrics.get("net_movement")), ("Transactions", metrics.get("transactions")),
           ("Fraud alerts", metrics.get("fraud_alerts")), ("Fraud alert rate", metrics.get("fraud_alert_rate")),
           ("Total exposure", metrics.get("total_exposure")), ("Active accounts", metrics.get("active_accounts"))]
    cards = "".join(f'<div class="kpi"><div class="kv">{_fmt(v)}</div><div class="kl">{k}</div></div>' for k, v in kpi)

    html = f"""<!doctype html><html><head><meta charset=utf-8><title>Bank Platform — Executive Dashboard</title>
<style>
 body{{font-family:system-ui,Segoe UI,sans-serif;margin:0;background:#0f1320;color:#e8edf5}}
 .wrap{{max-width:980px;margin:0 auto;padding:28px}}
 h1{{font-size:22px}} h2{{font-size:15px;color:#8fb6ff;margin:26px 0 10px}}
 .kpis{{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}}
 .kpi{{background:#161b26;border:1px solid #2a3447;border-radius:12px;padding:16px}}
 .kv{{font-size:24px;font-weight:700;color:#5fd6a4}} .kl{{font-size:12px;color:#aab4c4;margin-top:4px}}
 .bars{{background:#161b26;border:1px solid #2a3447;border-radius:12px;padding:14px}}
 .bar{{display:flex;align-items:center;gap:10px;margin:6px 0;font-size:12px}}
 .bl{{width:150px;color:#cdd5e0}} .bt{{height:14px;border-radius:4px}} .bv{{color:#aab4c4}}
 .note{{color:#8a97aa;font-size:12px;margin-top:24px}}
</style></head><body><div class="wrap">
<h1>🏦 Bank Data Platform — Executive Dashboard</h1>
<p class="note">Served from the governed <b>metrics layer</b> over the reconciled golden source. Same definitions feed Power BI / Looker / Tableau (see BI_CONNECT.md).</p>
<div class="kpis">{cards}</div>
<h2>Daily reconciliation — net movement</h2>{_bars(recon, 0, 3, '#5b9bff')}
<h2>Fraud alerts by country</h2>{_bars(fraud, 0, 1, '#ff6b6b')}
<h2>Regulatory exposure by region / segment</h2>{_bars(exposure, 0, 1, '#e3b341')}
<p class="note">Generated by serve_dashboard.py — the serving layer of the bank pipeline.</p>
</div></body></html>"""
    (OUT / "dashboard.html").write_text(html)
    print(f"   dashboard -> {OUT/'dashboard.html'}  | metrics: {json.dumps({k:_fmt(v) for k,v in metrics.items()})}")
    return metrics


if __name__ == "__main__":
    run()
